# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DockerCredentialSsoEcrLogin < Formula
  desc "Automatically gets credentials for Amazon ECR on docker push/docker pull with support for AWS SSO"
  homepage ""
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kyosenergy/docker-credential-sso-ecr-login/releases/download/v0.1.2/docker-credential-sso-ecr-login_darwin_amd64.tar.gz"
      sha256 "d88fe7f6daaa8f31b1db27e56b2882523279c9e734a9af9995a8ad4a62c0a814"

      def install
        bin.install "docker-credential-sso-ecr-login"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kyosenergy/docker-credential-sso-ecr-login/releases/download/v0.1.2/docker-credential-sso-ecr-login_darwin_arm64.tar.gz"
      sha256 "7c3a2c9e268c8a86ac31bdb10a308c000318c9e947589a6df30191d2a9b547c9"

      def install
        bin.install "docker-credential-sso-ecr-login"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyosenergy/docker-credential-sso-ecr-login/releases/download/v0.1.2/docker-credential-sso-ecr-login_linux_amd64.tar.gz"
        sha256 "d4cc59ec3380b1f728880aac26a933a23a6cd795248cafb4e408deb864da378b"

        def install
          bin.install "docker-credential-sso-ecr-login"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyosenergy/docker-credential-sso-ecr-login/releases/download/v0.1.2/docker-credential-sso-ecr-login_linux_arm64.tar.gz"
        sha256 "16bc5a848746fa51d9713f1fc90eeada7f4ae78c0a8b252276fbb61418303b8f"

        def install
          bin.install "docker-credential-sso-ecr-login"
        end
      end
    end
  end

  def post_install
    if OS.mac?
      ohai "We use `xattr` and `codesign` commands to make the binary executable"
      ohai "and self-signed, ensuring it runs correctly on macOS."

      system "/usr/bin/xattr", "-cr", "#{bin}/docker-credential-sso-ecr-login"
      system "/usr/bin/codesign", "--force", "--deep", "--sign", "-", "#{bin}/docker-credential-sso-ecr-login"
    end
  end

  test do
    "docker-credential-sso-ecr-login --version"
  end
end
