# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DockerCredentialSsoEcrLogin < Formula
  desc "Automatically gets credentials for Amazon ECR on docker push/docker pull with support for AWS SSO"
  homepage ""
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kyosenergy/docker-credential-sso-ecr-login/releases/download/v0.1.1/docker-credential-sso-ecr-login_darwin_amd64.tar.gz"
      sha256 "fb5a17c914b29571713dc445161e3dfe021488e255b67d2c2f0dafe9f1868ded"

      def install
        bin.install "docker-credential-sso-ecr-login"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kyosenergy/docker-credential-sso-ecr-login/releases/download/v0.1.1/docker-credential-sso-ecr-login_darwin_arm64.tar.gz"
      sha256 "d86c0dbed2d6f5864b5d336449bf7a042e8d006148ff7b5c0b97658bb9d9ae7b"

      def install
        bin.install "docker-credential-sso-ecr-login"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyosenergy/docker-credential-sso-ecr-login/releases/download/v0.1.1/docker-credential-sso-ecr-login_linux_amd64.tar.gz"
        sha256 "1b7492a3be1070bf35d503c371c369d8ead3e4ae4cdb162c1a07020b9dcde793"

        def install
          bin.install "docker-credential-sso-ecr-login"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyosenergy/docker-credential-sso-ecr-login/releases/download/v0.1.1/docker-credential-sso-ecr-login_linux_arm64.tar.gz"
        sha256 "e3f34783586e9ad397eaab103d394bd2d27c05c5023370c890524e4723c06a1b"

        def install
          bin.install "docker-credential-sso-ecr-login"
        end
      end
    end
  end

  def post_install
    if OS.mac?
      ohai "We use `xattr` and `codesign` commands to make the binary executable"
      ohai "and self-signed, ensuring it runs correctly on macOS."

      system "/usr/bin/xattr", "-cr", "#{bin}/docker-credential-sso-ecr-login"
      system "/usr/bin/codesign", "--force", "--deep", "--sign", "-", "#{bin}/docker-credential-sso-ecr-login"
    end
  end

  test do
    "docker-credential-sso-ecr-login --version"
  end
end
